In [3]:
import os
import sys
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re

def extractTable(city_url):
    url = city_url
    page = requests.get(url)
    soup = BeautifulSoup(page.content,"html.parser")
    city = soup.find("div",class_="titulo")
    city=city.text.split("\n")[1]

    mt5=soup.find("p",class_="mt5")
    latitude = re.findall("\d+\.\d+",mt5.text)[0]
    longitude = re.findall("\d+\.\d+",mt5.text)[1]

    data = []

    table= soup.find('table', attrs={'class':'medias'})

    rows = table.find_all('tr')

    for row in  rows:
        cols = row.find_all('td')
        cols = [ele.text.strip() for ele in cols]
        data.append(cols)
    
    df = pd.DataFrame(data, columns = ['Year','T','TM','Tm','PP','V','RA','SN','TS','FG','TN','GR'])

    cities = []
    for i in range (df.shape[0]):
                    cities.append(city)

    latitudes = []
    for i in range (df.shape[0]):
                    latitudes.append(latitude)

    longitudes = []
    for i in range (df.shape[0]):
                    longitudes.append(longitude)

    x= list(zip(cities,latitudes, longitudes))

    df_1 = pd.DataFrame(x, columns=['City','Latitude','Longitude'])

    completed_df = pd.concat([df_1,df],axis= 1)

    return completed_df

cities = pd.read_excel(r'C:\Users\abhij\python_project\url.xlsx')

final = pd.DataFrame()
for index, row in cities.iterrows():
    temp = extractTable(row['Url'])
    final = pd.concat([final,temp], axis=0)
print(final)

                                             City Latitude Longitude  Year  \
0    Climate BANGALORE Climate data:  1973 - 2022    12.96     77.58  None
1    Climate BANGALORE Climate data:  1973 - 2022    12.96     77.58  1973
2    Climate BANGALORE Climate data:  1973 - 2022    12.96     77.58  1974
3    Climate BANGALORE Climate data:  1973 - 2022    12.96     77.58  1975
4    Climate BANGALORE Climate data:  1973 - 2022    12.96     77.58  1976
..                                            ...      ...       ...   ...
46  Climate GOA/PANJIM Climate data:  1973 - 2022    15.48     73.81  2018
47  Climate GOA/PANJIM Climate data:  1973 - 2022    15.48     73.81  2019
48  Climate GOA/PANJIM Climate data:  1973 - 2022    15.48     73.81  2020
49  Climate GOA/PANJIM Climate data:  1973 - 2022    15.48     73.81  2021
50  Climate GOA/PANJIM Climate data:  1973 - 2022    15.48     73.81  2022

       T    TM    Tm       PP     V    RA    SN    TS    FG    TN    GR
0   None  None  None     None  None  None  None  None  None  None  None
1      -     -     -        -     -     -     -     -     -     -     -
2      -     -     -        -     -     -     -     -     -     -     -
3      -     -     -        -     -     -     -     -     -     -     -
4      -     -     -        -     -     -     -     -     -     -     -
..   ...   ...   ...      ...   ...   ...   ...   ...   ...   ...   ...
46  27.6  32.7  23.3        -   4.7   111     0    26     6     0     0
47  27.5  32.2  23.5  4087.81   5.6   128     1    21     3     0     0
48  27.7  31.8  23.8  4147.49   3.2   128     3    16     9     0     0
49  27.6  31.5  24.0  3425.47   2.0   141     0    27    24     0     0
50     -     -     -        -     -     -     -     -     -     -     -

[244 rows x 15 columns]